# Generated by Django 6.0.6 on 2026-06-30 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='F.I.Sh.')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='female', max_length=10, verbose_name='Jinsi')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yoshi')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name="Bo'yi (sm)")),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vazni (kg)')),
                ('glucose_mg_dl', models.FloatField(blank=True, null=True, verbose_name='Qon glyukozasi (mg/dL)')),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qon bosimi (yuqori)')),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qon bosimi (pastki)')),
                ('daily_steps', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kunlik qadamlar')),
                ('sleep_hours', models.FloatField(blank=True, null=True, verbose_name='Uyqu davomiyligi (soat)')),
                ('takes_medication', models.BooleanField(default=False, verbose_name='Dori qabul qilasizmi?')),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('digital_twin_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
